services:
  backend:
    image: vraj9115/url-backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - mern-network
    restart: unless-stopped

  frontend:
    image: vraj9115/url-frontend
    container_name: mern-frontend
    ports:
      - "3000:80"
    networks:
      - mern-network
    restart: unless-stopped

networks:
  mern-network:
